package compiler

import (
	"strings"
	"testing"

	"github.com/happypathnetworking/fylgja/internal/psp"
)

const bootstrapHeader = "# Generated by Fylgja: platform bootstrap only, nothing from intent.\n"

// twoPorts is a node's cabled ports as compile.go passes them: already in port order.
var twoPorts = []CabledPort{
	{Port: "e1-1", NodeName: "ethernet-1/1"},
	{Port: "e1-2", NodeName: "ethernet-1/2"},
}

// TestBootstrapPlaceholders pins which name each placeholder renders. SR Linux refuses
// containerlab's endpoint name in its configuration (`e1-1`; its own name for the port is
// `ethernet-1/1`), so a package must be able to ask for either name, and the compiler must not guess.
func TestBootstrapPlaceholders(t *testing.T) {
	cases := []struct {
		name     string
		template []string
		ports    []CabledPort
		want     []string
	}{
		{
			name:     "port line renders once per cabled port with the node port",
			template: []string{"set / interface {port} admin-state enable"},
			ports:    twoPorts,
			want: []string{
				"set / interface e1-1 admin-state enable",
				"set / interface e1-2 admin-state enable",
			},
		},
		{
			name:     "interface line renders once per cabled port with the node's name for it",
			template: []string{"set / interface {interface} admin-state enable"},
			ports:    twoPorts,
			want: []string{
				"set / interface ethernet-1/1 admin-state enable",
				"set / interface ethernet-1/2 admin-state enable",
			},
		},
		{
			// A lossy platform's node names its ports otherwise than production does, and
			// the node refuses a production name in its configuration.
			name:     "interface renders the node name, not the production name it was mapped from",
			template: []string{"interface {interface}"},
			ports:    []CabledPort{{Port: "eth1", NodeName: "Ethernet1"}, {Port: "eth49", NodeName: "Ethernet49"}},
			want:     []string{"interface Ethernet1", "interface Ethernet49"},
		},
		{
			name:     "a line using both renders once per port, each name from the same port",
			template: []string{"# {interface} is cabled as {port}"},
			ports:    twoPorts,
			want: []string{
				"# ethernet-1/1 is cabled as e1-1",
				"# ethernet-1/2 is cabled as e1-2",
			},
		},
		{
			name:     "a line with neither renders once",
			template: []string{"set / system lldp admin-state enable"},
			ports:    twoPorts,
			want:     []string{"set / system lldp admin-state enable"},
		},
		{
			name: "node substitutes everywhere, including per-port lines and repeats",
			template: []string{
				"set / system name host-name {node}",
				"# {node} port {port} on {node}",
			},
			ports: twoPorts,
			want: []string{
				"set / system name host-name n1",
				"# n1 port e1-1 on n1",
				"# n1 port e1-2 on n1",
			},
		},
		{
			name: "per-port lines expand in place, keeping the template's line order",
			template: []string{
				"set / system name host-name {node}",
				"set / interface {interface} admin-state enable",
				"set / system lldp admin-state enable",
			},
			ports: twoPorts,
			want: []string{
				"set / system name host-name n1",
				"set / interface ethernet-1/1 admin-state enable",
				"set / interface ethernet-1/2 admin-state enable",
				"set / system lldp admin-state enable",
			},
		},
		{
			name:     "a per-port line renders nothing on a node with no cabled ports",
			template: []string{"set / interface {interface} admin-state enable", "set / system lldp admin-state enable"},
			ports:    nil,
			want:     []string{"set / system lldp admin-state enable"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			p := &psp.PSP{Config: psp.Config{Bootstrap: tc.template}}
			got := string(renderBootstrap(p, "n1", tc.ports))
			want := bootstrapHeader + strings.Join(tc.want, "\n") + "\n"
			if got != want {
				t.Errorf("rendered:\n%s\nwant:\n%s", got, want)
			}
		})
	}
}

// TestShippedBootstrapNamesTheNOSInterface guards the package line M2 corrected: the
// SR Linux template must render the NOS's own interface name, never the endpoint name.
func TestShippedBootstrapNamesTheNOSInterface(t *testing.T) {
	got := string(renderBootstrap(srlinux(t), "n1", twoPorts))
	if strings.Contains(got, "interface e1-") {
		t.Errorf("SR Linux bootstrap renders containerlab's endpoint name, which the NOS refuses:\n%s", got)
	}
	if !strings.Contains(got, "set / interface ethernet-1/1 admin-state enable\n") {
		t.Errorf("SR Linux bootstrap does not enable ethernet-1/1:\n%s", got)
	}
}

// The generated header is written under the package's comment marker, and a package
// that names none means "#", which is what every package written before the field
// meant — so no existing package, bundle or bundle_id moves for it.
//
// This is not cosmetic. A package whose bootstrap reaches the node through the push has
// this header sent to the node as a command like every other line of the file, so a
// marker that node does not read as a comment is refused, and under an atomic commit
// nothing lands.
func TestBootstrapHeaderUsesThePackagesCommentMarker(t *testing.T) {
	for _, tc := range []struct {
		name, prefix, want string
	}{
		{"a package that names none means #", "", "# Generated by Fylgja: platform bootstrap only, nothing from intent."},
		{"a package that names one is obeyed", "!", "! Generated by Fylgja: platform bootstrap only, nothing from intent."},
		{"a marker of more than one character", "//", "// Generated by Fylgja: platform bootstrap only, nothing from intent."},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := &psp.PSP{Config: psp.Config{CommentPrefix: tc.prefix, Bootstrap: []string{"hostname {node}"}}}
			got := strings.Split(string(renderBootstrap(p, "n1", nil)), "\n")
			if got[0] != tc.want {
				t.Errorf("header = %q, want %q", got[0], tc.want)
			}
			if got[1] != "hostname n1" {
				t.Errorf("line 2 = %q, want the bootstrap's own line", got[1])
			}
		})
	}
}

// Both shipped packages render a header their own node reads as a comment, and neither
// renders the other's marker. The shipped SR Linux package names no marker, so the bytes
// of every bundle built from it — the three-node golden included — are where M6 left
// them, which is what keeps this an additive field.
func TestShippedPackagesRenderTheirOwnHeader(t *testing.T) {
	reg, err := psp.Load("")
	if err != nil {
		t.Fatal(err)
	}
	for _, tc := range []struct{ nos, want string }{
		{"srlinux", "#"},
		{"eos", "!"},
	} {
		p, ok := reg.Lookup(tc.nos)
		if !ok {
			t.Fatalf("no shipped package for nos %s", tc.nos)
		}
		header, _, _ := strings.Cut(string(renderBootstrap(p, "n1", nil)), "\n")
		if marker, _, _ := strings.Cut(header, " "); marker != tc.want {
			t.Errorf("%s renders header %q, want it to open with %q", p.Platform.ID, header, tc.want)
		}
	}
}
