package compiler

import (
	"strings"

	"github.com/happypathnetworking/fylgja/internal/psp"
)

// CabledPort is one cabled port on a node, under both names a bootstrap line may need.
type CabledPort struct {
	Port     string // the node port: containerlab's endpoint name, e.g. e1-1
	NodeName string // the node's own name for the port, as the profile's rule renders it, e.g. ethernet-1/1
}

// renderBootstrap produces one node's startup configuration.
//
// Platform bootstrap only: enough for the node to come up, be reachable, and form
// link-layer adjacencies on its cabled ports. Nothing here comes from intent — no
// addresses, no protocols, no policy. Fylgja does not render configuration
// (Constitution IV); the template is data owned by the platform's support package, and
// this function substitutes a node name and the cabled ports into it.
//
// The file opens with one generated header line, written under the comment marker the
// package declares (config.comment_prefix, defaulting to "#"). The marker is data
// because a package whose bootstrap reaches the node through the push has that header
// sent to the node as a command like every other line of the file, and a node that does
// not read the marker as a comment refuses it and, under an atomic commit, lands nothing
// at all: one confirmed system reads "!" there and rejects "#" outright. Which marker a
// node reads is the package's to say, as its bootstrap template is:
// no platform logic enters the compiler (Constitution II).
//
// {node} renders the node name wherever it appears. A line containing {port} or
// {interface} is emitted once per cabled port, in the order given: {port} renders the
// node port, the name containerlab gives the endpoint; {interface} renders the node's
// own name for that port, as the profile's rule for it declares. A NOS refuses
// the endpoint name in its configuration, and on a platform
// that names its ports as production the node name is the production name, so those
// bytes are M2's. Which name a platform's configuration needs is the package's choice,
// made in its template: no platform logic enters the compiler (Constitution II).
//
// Configuring what intent actually says arrives at M5, through Infrahub artifacts.
func renderBootstrap(p *psp.PSP, node string, cabledPorts []CabledPort) []byte {
	var b strings.Builder
	b.WriteString(p.Config.CommentPrefixOrDefault() + " Generated by Fylgja: platform bootstrap only, nothing from intent.\n")
	for _, line := range p.Config.Bootstrap {
		if strings.Contains(line, "{port}") || strings.Contains(line, "{interface}") {
			for _, cp := range cabledPorts {
				// One pass, so a substituted name is never itself re-substituted.
				r := strings.NewReplacer("{port}", cp.Port, "{interface}", cp.NodeName, "{node}", node)
				b.WriteString(r.Replace(line))
				b.WriteString("\n")
			}
			continue
		}
		b.WriteString(strings.ReplaceAll(line, "{node}", node))
		b.WriteString("\n")
	}
	return []byte(b.String())
}
