package compiler

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// LabName is the containerlab lab name, and it is a constant.
//
// One twin at a time (D-013): a name derived from the branch would let two twins
// coexist, so the collision M2 must refuse would have to be enforced by policy
// somewhere else. Fixed here, a second twin collides by construction. It also keeps
// the branch out of the bundle's bytes, so the same intent read from a renamed branch
// still compiles to the same bundle_id (D-011).
const LabName = "fylgja"

// Bundle layout — the file names the compiler emits, and the contract with M2.
// internal/bundle writes whatever paths it is handed; these are where they come from.
const (
	TopologyFile = "topology.clab.yml"
	ManifestFile = "manifest.json"
	ConfigsDir   = "configs"
)

// CabledLink is one veth pair in the twin, in node-port terms.
type CabledLink struct {
	ID string   `json:"id"`
	A  NodePort `json:"a"`
	B  NodePort `json:"b"`
}

// NodePort names one side of a cabled link.
type NodePort struct {
	Node string `json:"node"`
	Port string `json:"port"`
}

// TopologyNode is one node in the deployment topology.
type TopologyNode struct {
	Name  string
	Kind  string
	Image string
	// StartupConfig is empty for a node whose package says its bootstrap reaches it
	// through the push; renderTopology then writes no startup-config key for it.
	StartupConfig string
}

// yamlMap builds an ordered YAML mapping. Go map iteration is randomized, so anything
// that reaches the file goes through here: ordering is part of the bundle contract,
// not an accident of the runtime.
func yamlMap(pairs ...any) *yaml.Node {
	n := &yaml.Node{Kind: yaml.MappingNode}
	for i := 0; i < len(pairs); i += 2 {
		key := &yaml.Node{Kind: yaml.ScalarNode, Value: pairs[i].(string)}
		var val *yaml.Node
		switch v := pairs[i+1].(type) {
		case *yaml.Node:
			val = v
		case string:
			val = &yaml.Node{Kind: yaml.ScalarNode, Value: v}
		default:
			val = &yaml.Node{Kind: yaml.ScalarNode, Value: fmt.Sprint(v)}
		}
		n.Content = append(n.Content, key, val)
	}
	return n
}

// renderTopology emits the containerlab topology.
//
// containerlab's own format is the output, not a Fylgja-neutral one that M2 would have
// to translate: the compiler's product is the deployment input, and `clab` is driven
// through its CLI (D-008). A bundle is therefore deployable with nothing but the
// bundle directory.
//
// No `mgmt` block is emitted: containerlab's default management network is the one
// the twin uses, so the bundle neither names an address range nor depends on one
// being free (D-011).
func renderTopology(nodes []TopologyNode, links []CabledLink) ([]byte, error) {
	sorted := make([]TopologyNode, len(nodes))
	copy(sorted, nodes)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	nodesNode := &yaml.Node{Kind: yaml.MappingNode}
	for _, n := range sorted {
		// A node whose package sends its bootstrap through the push carries no
		// startup-config: on a kind that takes such a file as the whole configuration
		// rather than a snippet merged over its default, naming it here would boot the
		// node with the bootstrap alone and nothing else. The file is
		// still written and still named in the manifest.
		pairs := []any{"kind", n.Kind, "image", n.Image}
		if n.StartupConfig != "" {
			pairs = append(pairs, "startup-config", n.StartupConfig)
		}
		nodesNode.Content = append(nodesNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: n.Name},
			yamlMap(pairs...))
	}

	sortedLinks := make([]CabledLink, len(links))
	copy(sortedLinks, links)
	sort.SliceStable(sortedLinks, func(i, j int) bool { return sortedLinks[i].ID < sortedLinks[j].ID })

	linksNode := &yaml.Node{Kind: yaml.SequenceNode}
	for _, l := range sortedLinks {
		eps := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle}
		eps.Content = append(eps.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: l.A.Node + ":" + l.A.Port, Style: yaml.DoubleQuotedStyle},
			&yaml.Node{Kind: yaml.ScalarNode, Value: l.B.Node + ":" + l.B.Port, Style: yaml.DoubleQuotedStyle})
		linksNode.Content = append(linksNode.Content, yamlMap("endpoints", eps))
	}

	root := yamlMap("name", LabName, "topology", yamlMap("nodes", nodesNode, "links", linksNode))

	var b strings.Builder
	b.WriteString("# Generated by Fylgja. Do not edit: rebuild from intent instead.\n")
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}
