package lab

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"reflect"
	"strings"
	"sync"
	"testing"
	"time"

	"go.temporal.io/sdk/temporal"

	"github.com/happypathnetworking/fylgja/internal/findings"
	"github.com/happypathnetworking/fylgja/internal/lab/wire"
	"github.com/happypathnetworking/fylgja/internal/psp"
)

// eapiArtifact is a small artifact of the shape a CLI rendering has for this mechanism: a
// comment line, a host name, and two interface blocks with indented lines, the last of
// which the node will refuse. Its own line numbers are what a refusal must re-base onto:
// line 3 is empty and not sent, so the node counts one command fewer than the file has
// lines from there on.
const eapiArtifact = "! n1: " + pushMarker + "\n" +
	"hostname n1\n" +
	"\n" +
	"interface Ethernet1\n" +
	"   description to n2 Ethernet1\n" +
	"   no shutdown\n" +
	"interface Ethernet2\n" +
	"   frobnicate 1\n"

// eapiBootstrap is the bootstrap of a package whose bootstrap reaches the node through the
// push: the compiler's generated header, then the one line the package declares. Line 2 is
// empty and not sent, so its last line is its third and the node's second command of it.
const eapiBootstrap = "! generated by fylgja\n" +
	"\n" +
	"hostname n1\n"

// eapiLines and bootstrapLines are those files' lines as they are sent: comments kept,
// empty dropped.
func eapiLines() []string      { return texts(configCommands([]byte(eapiArtifact), false)) }
func bootstrapLines() []string { return texts(configCommands([]byte(eapiBootstrap), true)) }

// eapiPush is a package's push as this mechanism takes it: the command API over HTTPS
// with a login of its own, an explicit commit, merge. Every value is
// the package's data; the code under test reads it and names no platform.
func eapiPush() wire.PushSpec {
	return wire.PushSpec{
		Delivery: DeliveryEAPI, Mode: "merge", Commit: "explicit", Scheme: "https", Port: 443,
		UsernameEnv: "FYLGJA_EOS_USERNAME", PasswordEnv: "FYLGJA_EOS_PASSWORD", TimeoutS: 30,
	}
}

// eapiNode is a fake command-API endpoint: it keeps each request it is sent and the
// answer format it asked for, refusing anything that is not a runCmds call in one of the
// two formats the mechanism sends, and answers with answer.
type eapiNode struct {
	answer func(w http.ResponseWriter, r *http.Request, cmds []string)

	mu       sync.Mutex
	commands [][]string
	formats  []string
	logins   []string
}

func (n *eapiNode) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var req eapiCall
	if r.URL.Path != eapiPath || r.Method != http.MethodPost || json.NewDecoder(r.Body).Decode(&req) != nil ||
		req.Method != "runCmds" || req.JSONRPC != "2.0" || req.Params.Version != 1 ||
		(req.Params.Format != eapiFormatJSON && req.Params.Format != eapiFormatText) {
		http.Error(w, "not a runCmds request", http.StatusBadRequest)
		return
	}
	u, p, _ := r.BasicAuth()
	n.mu.Lock()
	n.commands = append(n.commands, req.Params.Commands)
	n.formats = append(n.formats, req.Params.Format)
	n.logins = append(n.logins, u+":"+p)
	n.mu.Unlock()
	n.answer(w, r, req.Params.Commands)
}

// sentFormats returns the answer format each request asked for, in order.
func (n *eapiNode) sentFormats() []string {
	n.mu.Lock()
	defer n.mu.Unlock()
	return append([]string(nil), n.formats...)
}

// sent returns the requests the node was sent so far.
func (n *eapiNode) sent() [][]string {
	n.mu.Lock()
	defer n.mu.Unlock()
	out := make([][]string, len(n.commands))
	copy(out, n.commands)
	return out
}

// eapiRan answers as a node that ran every command: one result entry each, nothing to say.
func eapiRan(w http.ResponseWriter, _ *http.Request, cmds []string) {
	eapiRanWithWarnings()(w, nil, cmds)
}

// eapiRanWithWarnings answers success with a warning on each of the given 1-based command
// indices, as cEOS 4.32.0.2F answers a configuration naming an interface it lacks.
func eapiRanWithWarnings(at ...int) func(http.ResponseWriter, *http.Request, []string) {
	return func(w http.ResponseWriter, _ *http.Request, cmds []string) {
		result := make([]map[string]any, len(cmds))
		for i := range result {
			result[i] = map[string]any{}
		}
		for _, n := range at {
			result[n-1] = map[string]any{"warnings": []string{
				"Interface does not exist. The configuration will not take effect until the module is inserted."}}
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "result": result})
	}
}

// eapiFailedAt answers as cEOS 4.32.0.2F answers a command it will not run: HTTP
// 200, a JSON-RPC error whose message echoes the command and whose data holds one entry
// per command run, the last carrying the reason.
func eapiFailedAt(nth int, reasons ...string) func(http.ResponseWriter, *http.Request, []string) {
	return func(w http.ResponseWriter, r *http.Request, cmds []string) {
		// A shorter list than the push's is the abort that follows a refusal, which this
		// node runs: only the push itself has a command the node will not run.
		if nth > len(cmds) {
			eapiRan(w, r, cmds)
			return
		}
		data := make([]map[string]any, nth)
		for i := range data {
			data[i] = map[string]any{}
		}
		data[nth-1] = map[string]any{"errors": reasons}
		_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{
			"code":    1002,
			"message": fmt.Sprintf("CLI command %d of %d '%s' failed: invalid command", nth, len(cmds), cmds[nth-1]),
			"data":    data,
		}})
	}
}

// eapiSetup stages eapiArtifact and eapiBootstrap as n1's under a fresh state root, with
// the bootstrap applied via, and serves node over TLS.
func eapiSetup(t *testing.T, node http.Handler, via string) (*Activities, wire.PushInput, *bytes.Buffer) {
	t.Helper()
	a := testActivities(t, &fakeRunner{})
	a.Getenv = mapEnv(map[string]string{"FYLGJA_EOS_USERNAME": "admin", "FYLGJA_EOS_PASSWORD": pushPassword})
	var log bytes.Buffer
	a.Log = slog.New(slog.NewTextHandler(&log, &slog.HandlerOptions{Level: slog.LevelDebug}))

	checksum := stagePush(t, a, stagedBundle{artifact: eapiArtifact, bootstrap: eapiBootstrap, via: via})
	host, port := pushNodeAt(t, node)
	push := eapiPush()
	push.Port = port
	return a, wire.PushInput{
		Node: "n1", MgmtIPv4: host, TwinDir: a.Paths.Twin, Artifact: "configs/n1.device-config",
		Checksum: checksum, Push: push,
	}, &log
}

// sessionName is the configuration session one request named, or "" if it named none.
func sessionName(cmds []string) string {
	for _, c := range cmds {
		if name, ok := strings.CutPrefix(c, cmdSession); ok {
			return name
		}
	}
	return ""
}

// The mechanism's own request: one POST of one command list, privileged mode first, a
// configuration session named for the attempt, the artifact's lines as they are with
// empty ones dropped, and the commit — under the package's login, and nothing that
// surfaces carrying the configuration or the password.
func TestPushEAPICommitsInOneRequest(t *testing.T) {
	node := &eapiNode{answer: eapiRan}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)

	res, beats, err := pushOnce(t, a, in)
	if err != nil {
		t.Fatal(err)
	}
	sent := node.sent()
	if len(sent) != 1 {
		t.Fatalf("the node was sent %d requests, want one", len(sent))
	}
	session := sessionName(sent[0])
	want := append(append([]string{cmdEnable, cmdSession + session}, eapiLines()...), cmdCommit)
	if !reflect.DeepEqual(sent[0], want) {
		t.Errorf("node was sent %q,\nwant %q", sent[0], want)
	}
	// fylgja-<attempt>-<unix nanoseconds>: a committed name cannot be reused.
	if !strings.HasPrefix(session, eapiSessionPrefix+"1-") || len(session) <= len(eapiSessionPrefix)+2 {
		t.Errorf("session %q, want %s<attempt>-<unix ns>", session, eapiSessionPrefix)
	}
	if node.logins[0] != "admin:"+pushPassword {
		t.Errorf("login = %q, want the package's variables' values", node.logins[0])
	}
	// Under merge the request is M7's, answered as JSON, and asks for no diff.
	if got := node.sentFormats(); !reflect.DeepEqual(got, []string{eapiFormatJSON}) {
		t.Errorf("formats = %q, want [json] under merge", got)
	}
	if res.Node != "n1" || res.Checksum != in.Checksum || res.Size != len(eapiArtifact) || res.PushedInS <= 0 || res.Diff != "" {
		t.Errorf("result = %+v, want n1 with the checksum, %d bytes, a duration and no diff", res, len(eapiArtifact))
	}
	if beats < 1 {
		t.Error("the push sent no heartbeat before its request")
	}

	b, err := json.Marshal(struct {
		In  wire.PushInput
		Res wire.PushResult
	}{in, res})
	if err != nil {
		t.Fatal(err)
	}
	noContent(t, "the push's input and result", string(b))
	noContent(t, "the push's log", log.String())
	// The by_hand line names the login by its variables and the file by its staged path.
	for _, want := range []string{"pushed", "delivery=" + DeliveryEAPI, "artifact=device-config",
		"checksum=" + in.Checksum, `$FYLGJA_EOS_USERNAME:$FYLGJA_EOS_PASSWORD`, eapiPath, `configure session by-hand`} {
		if !strings.Contains(log.String(), want) {
			t.Errorf("log does not say %q:\n%s", want, log.String())
		}
	}
}

// With an implicit commit the list opens the configuration directly and ends it. Nothing
// shipped declares it; the arm exists because the format value does.
func TestPushEAPIImplicitCommit(t *testing.T) {
	node := &eapiNode{answer: eapiRan}
	a, in, _ := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
	in.Push.Commit = "implicit"
	if _, _, err := pushOnce(t, a, in); err != nil {
		t.Fatal(err)
	}
	want := append(append([]string{cmdEnable, cmdConfigure}, eapiLines()...), cmdEnd)
	if !reflect.DeepEqual(node.sent()[0], want) {
		t.Errorf("node was sent %q,\nwant %q", node.sent()[0], want)
	}
}

// Mode replace with an implicit commit has no command list for this mechanism: the reset
// loads the baseline into a session, which an implicit commit has none of. Refused before
// any request, and not retried, as M5 refuses the pair.
func TestPushEAPIRefusesReplaceImplicit(t *testing.T) {
	node := &eapiNode{answer: eapiRan}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
	in.Push.Mode, in.Push.Commit = "replace", "implicit"
	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushFailed)
	const want = "mode replace with commit implicit has no command list for delivery eapi: " +
		"the reset loads the baseline into a candidate and commits it, which an implicit commit has none of"
	if !strings.Contains(f.Message, want) || len(node.sent()) != 0 {
		t.Errorf("finding %+v after %d requests, want %q and nothing sent", f, len(node.sent()), want)
	}
	noContent(t, "a refused mode", f.Message, err.Error(), log.String())
}

// sessionDiff is cEOS's diff entry for a session that differs from running by a
// description: the device's words, and configuration, which nothing but the push's result
// may carry.
const sessionDiff = "--- system:/running-config\n" +
	"+++ session:/fylgja-1-session-config\n" +
	"+interface Ethernet1\n" +
	"+   description to n2 Ethernet1\n"

// eapiRanWithDiff answers as cEOS answers a replace under format text: one
// {"output": …} entry per command, the diff command's carrying diff.
func eapiRanWithDiff(diff string) func(http.ResponseWriter, *http.Request, []string) {
	return func(w http.ResponseWriter, _ *http.Request, cmds []string) {
		result := make([]map[string]any, len(cmds))
		for i, c := range cmds {
			result[i] = map[string]any{"output": ""}
			if c == cmdSessionDiff {
				result[i] = map[string]any{"output": diff}
			}
			if c == cmdCopyStartup {
				result[i]["messages"] = []string{"Copy completed successfully."}
			}
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "result": result})
	}
}

// The shipped package's push (M11 D-033): one request, answered as text,
// of privileged mode, the session, `rollback clean-config` and `copy startup-config
// session-config`, the bootstrap's lines whatever bootstrap_via says, the
// artifact's, `show session-config diffs` and `commit`. The result carries the diff
// entry's output, "" when the session equals running, and the log its length alone.
func TestPushEAPIReplaceInOneRequest(t *testing.T) {
	for _, c := range []struct {
		via, diff string
	}{
		{psp.BootstrapViaPush, sessionDiff},
		{psp.BootstrapViaStartupConfig, sessionDiff},
		{psp.BootstrapViaPush, ""},
	} {
		t.Run(fmt.Sprintf("%s/diff %d bytes", c.via, len(c.diff)), func(t *testing.T) {
			node := &eapiNode{answer: eapiRanWithDiff(c.diff)}
			a, in, log := eapiSetup(t, node, c.via)
			in.Push.Mode = psp.ModeReplace

			res, _, err := pushOnce(t, a, in)
			if err != nil {
				t.Fatal(err)
			}
			sent := node.sent()
			if len(sent) != 1 {
				t.Fatalf("the node was sent %d requests, want one", len(sent))
			}
			want := append([]string{cmdEnable, cmdSession + sessionName(sent[0]), cmdRollbackClean, cmdCopyStartup}, bootstrapLines()...)
			want = append(append(want, eapiLines()...), cmdSessionDiff, cmdCommit)
			if !reflect.DeepEqual(sent[0], want) {
				t.Errorf("node was sent %q,\nwant %q", sent[0], want)
			}
			// The diff command has no JSON model: under json the whole request fails with
			// 1003 and leaves its session pending.
			if got := node.sentFormats(); !reflect.DeepEqual(got, []string{eapiFormatText}) {
				t.Errorf("formats = %q, want [text] under replace", got)
			}
			if res.Diff != c.diff {
				t.Errorf("result diff = %q, want the diff entry's output %q", res.Diff, c.diff)
			}
			if !strings.Contains(log.String(), fmt.Sprintf("diff_bytes=%d", len(c.diff))) {
				t.Errorf("the log does not name the diff's length:\n%s", log.String())
			}
			for _, line := range []string{"+interface Ethernet1", "+++ session:", "--- system:"} {
				if strings.Contains(log.String(), line) {
					t.Errorf("the log carries the diff's %q:\n%s", line, log.String())
				}
			}
			noContent(t, "the push's log", log.String())
		})
	}
}

// A replace the node refuses is push.refused at the artifact's own line, re-based through
// the replace's longer list, and its session is aborted before the next attempt, as M7
// does: the abort is M7's request, answered as JSON.
func TestPushEAPIReplaceRefusedIsAborted(t *testing.T) {
	const reason = "Invalid input (at token 0: 'frobnicate')"
	// enable, the session, the reset's two, the bootstrap's two sent lines, then the
	// artifact's seven: command 13 is the artifact's last, its file line 8.
	node := &eapiNode{answer: eapiFailedAt(13, reason)}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaPush)
	in.Push.Mode = psp.ModeReplace

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at line 8: %s", in.Checksum, reason)
	if f.Message != want {
		t.Errorf("finding message = %q,\nwant %q", f.Message, want)
	}
	for _, line := range []string{"insert /", "delete /", "update /", "replace /", "+interface"} {
		if strings.Contains(f.Message, line) {
			t.Errorf("the refusal carries %q: %s", line, f.Message)
		}
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
	sent := node.sent()
	if len(sent) != 2 || !reflect.DeepEqual(sent[1], []string{cmdEnable, cmdSession + sessionName(sent[0]), cmdAbort}) {
		t.Fatalf("the node was sent %q, want the push and its session aborted", sent)
	}
	if got := node.sentFormats(); !reflect.DeepEqual(got, []string{eapiFormatText, eapiFormatJSON}) {
		t.Errorf("formats = %q, want the replace as text and the abort as M7's json", got)
	}
}

// A line the node will not run is push.refused, final, naming the node, the artifact, its
// checksum, the artifact's own line and the node's reason — and none of the command the
// node echoed. The line is re-based through the command list, so the dropped empty line
// is counted: the node's command 9 is the file's line 8.
func TestPushEAPIRefusedArtifactLine(t *testing.T) {
	const reason = "Invalid input (at token 0: 'frobnicate')"
	node := &eapiNode{answer: eapiFailedAt(9, reason)}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at line 8: %s", in.Checksum, reason)
	if f.Message != want || f.Step != findings.StepPush || f.Object != "n1" {
		t.Errorf("finding = %+v\nwant message %q at step push on n1", f, want)
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
	// The node's message echoed the command it refused, and its errors echo a token of
	// it; the refusal keeps the reason and drops the echo (Constitution X).
	for _, c := range eapiLines() {
		if strings.Contains(f.Message, c) {
			t.Errorf("the refusal carries the echoed command %q: %s", c, f.Message)
		}
	}
	// Nothing landed, so the session the attempt named is aborted, best effort.
	sent := node.sent()
	if len(sent) != 2 {
		t.Fatalf("the node was sent %d requests, want the push and the abort", len(sent))
	}
	session := sessionName(sent[0])
	if !reflect.DeepEqual(sent[1], []string{cmdEnable, cmdSession + session, cmdAbort}) {
		t.Errorf("the second request was %q, want the refused session aborted", sent[1])
	}
	if !strings.Contains(log.String(), "aborted") || !strings.Contains(log.String(), session) {
		t.Errorf("the log does not say the session was aborted:\n%s", log.String())
	}
}

// An abort that outlasts the push's budget leaves the refusal a refusal: push.refused,
// final, as the node worded it, never a push.failed that is retried. The abort is M7's
// courtesy and cannot fail the run; the dispatch tells a refusal before the budget
// (M11 D-034, which asks the json_rpc arm's reason in a request of its own the same way).
func TestPushEAPIRefusalOutlastsItsAbort(t *testing.T) {
	const reason = "Invalid input (at token 0: 'frobnicate')"
	refuse := eapiFailedAt(9, reason)
	node := &eapiNode{answer: func(w http.ResponseWriter, r *http.Request, cmds []string) {
		if len(cmds) > 0 && cmds[len(cmds)-1] == cmdAbort {
			select {
			case <-r.Context().Done():
			case <-time.After(10 * time.Second):
			}
			return
		}
		refuse(w, r, cmds)
	}}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
	in.Push.TimeoutS = 1

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	if want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at line 8: %s", in.Checksum, reason); f.Message != want {
		t.Errorf("finding message = %q,\nwant %q", f.Message, want)
	}
	if !strings.Contains(log.String(), "could not be aborted") {
		t.Errorf("the log does not say the abort failed:\n%s", log.String())
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
}

// The bootstrap goes through the push when the staged manifest says so, ahead of the
// artifact's lines and inside the same session, so one commit lands both. A refusal
// of one of its lines says which file the line is in.
func TestPushEAPISendsTheBootstrapFromTheStagedManifest(t *testing.T) {
	t.Run("sent ahead of the artifact", func(t *testing.T) {
		node := &eapiNode{answer: eapiRan}
		a, in, _ := eapiSetup(t, node, psp.BootstrapViaPush)
		if _, _, err := pushOnce(t, a, in); err != nil {
			t.Fatal(err)
		}
		sent := node.sent()[0]
		want := append([]string{cmdEnable, cmdSession + sessionName(sent)}, bootstrapLines()...)
		want = append(append(want, eapiLines()...), cmdCommit)
		if !reflect.DeepEqual(sent, want) {
			t.Errorf("node was sent %q,\nwant %q", sent, want)
		}
	})

	t.Run("a refused bootstrap line", func(t *testing.T) {
		const reason = "Invalid input (at token 0: 'hostname')"
		// Command 4 of the list is the bootstrap's second sent line, its file line 3.
		node := &eapiNode{answer: eapiFailedAt(4, reason)}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaPush)

		_, _, err := pushOnce(t, a, in)
		f := stepFailure(t, err, findings.RulePushRefused)
		want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at bootstrap line 3: %s", in.Checksum, reason)
		if f.Message != want {
			t.Errorf("finding message = %q,\nwant %q", f.Message, want)
		}
		noContent(t, "a refused bootstrap line", f.Message, err.Error(), log.String())
	})

	t.Run("not sent when the manifest says startup_config", func(t *testing.T) {
		node := &eapiNode{answer: eapiRan}
		a, in, _ := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		if _, _, err := pushOnce(t, a, in); err != nil {
			t.Fatal(err)
		}
		for _, c := range node.sent()[0] {
			if c == "! generated by fylgja" {
				t.Error("the bootstrap was sent though the manifest says the lab tool applies it")
			}
		}
	})
}

// A framing command the node will not run is the mechanism's own failure, not the
// configuration's: push.failed, retried, and the next attempt names a session no commit
// has taken.
func TestPushEAPIFramingFailureIsRetried(t *testing.T) {
	const reason = "Cannot enter session (already completed)"
	node := &eapiNode{answer: eapiFailedAt(2, reason)}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)

	_, _, err := pushOnce(t, a, in)
	f := retryableFailure(t, err)
	if !strings.Contains(f.Message, "the framing command `"+cmdSession) || !strings.Contains(f.Message, "failed: "+reason) {
		t.Errorf("finding = %+v, want the framing command and the node's reason", f)
	}
	noContent(t, "a framing failure", f.Message, err.Error(), log.String())

	// The same input again: a fresh session name, so a name a commit took cannot block
	// the retry for ever.
	if _, _, err := pushOnce(t, a, in); err == nil {
		t.Fatal("the second attempt succeeded against a node that refuses its session")
	}
	sent := node.sent()
	first, second := sessionName(sent[0]), sessionName(sent[len(sent)-1])
	if first == "" || first == second {
		t.Errorf("attempts named sessions %q and %q, want a fresh name per attempt", first, second)
	}
}

// An error answer that does not say which command failed is withheld whole: its message
// echoes the command.
func TestPushEAPIWithholdsAnAnswerItCannotRead(t *testing.T) {
	for _, c := range []struct {
		name   string
		answer func(http.ResponseWriter, *http.Request, []string)
		want   string
	}{
		{name: "no data", want: "does not say which command it refused",
			answer: func(w http.ResponseWriter, _ *http.Request, cmds []string) {
				_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{
					"code": 1002, "message": "CLI command 3 of 4 '" + pushMarker + "' failed"}})
			}},
		{name: "no reason", want: "the node gave no reason",
			answer: eapiFailedAt(9)},
	} {
		t.Run(c.name, func(t *testing.T) {
			node := &eapiNode{answer: c.answer}
			a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
			_, _, err := pushOnce(t, a, in)
			f := stepFailure(t, err, findings.RulePushRefused)
			if !strings.Contains(f.Message, c.want) {
				t.Errorf("finding = %+v, want %q", f, c.want)
			}
			noContent(t, "a withheld answer", f.Message, err.Error(), log.String())
		})
	}
}

// Warnings are counted and their lines named, never their text, and they are not a
// finding: the push succeeded.
func TestPushEAPICountsWarnings(t *testing.T) {
	// With the bootstrap pushed the list is enable, the session, the bootstrap's two sent
	// lines, the artifact's seven, and the commit: commands 3 and 4 are the bootstrap's
	// lines 1 and 3, commands 8 and 11 the artifact's lines 5 and 8, and command 1 the
	// framing `enable`.
	node := &eapiNode{answer: eapiRanWithWarnings(3, 4, 8, 11, 1)}
	a, in, log := eapiSetup(t, node, psp.BootstrapViaPush)

	if _, _, err := pushOnce(t, a, in); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"node n1 warned on 2 lines of artifact device-config (lines 5, 8)",
		"node n1 warned on 2 lines of its bootstrap (lines 1, 3)",
		"node n1 warned on 1 framing command",
	} {
		if !strings.Contains(log.String(), want) {
			t.Errorf("the log does not say %q:\n%s", want, log.String())
		}
	}
	if strings.Contains(log.String(), "Interface does not exist") {
		t.Errorf("the log quotes a warning's text:\n%s", log.String())
	}
	noContent(t, "the warnings", log.String())
}

// The transport's failures are M5's shapes, worded for this mechanism's endpoint: a status
// that is not 2xx, a login refused with the variables named, a body that is not an answer,
// a body longer than the limit, and a node that does not answer within the budget. Each is
// push.failed and retried, and none quotes the node's body.
func TestPushEAPITransportFailures(t *testing.T) {
	t.Run("401", func(t *testing.T) {
		node := &eapiNode{answer: func(w http.ResponseWriter, _ *http.Request, _ []string) {
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
		}}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "401") || !strings.Contains(f.Message, "FYLGJA_EOS_USERNAME/FYLGJA_EOS_PASSWORD") ||
			!strings.Contains(f.Message, eapiPath) {
			t.Errorf("finding = %+v, want the status, the endpoint and the login's variable names", f)
		}
		noContent(t, "a 401", f.Message, err.Error(), log.String())
	})
	t.Run("500", func(t *testing.T) {
		node := &eapiNode{answer: func(w http.ResponseWriter, _ *http.Request, cmds []string) {
			http.Error(w, strings.Join(cmds, "\n"), http.StatusInternalServerError)
		}}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "500") {
			t.Errorf("finding = %+v, want the status", f)
		}
		noContent(t, "a 500", f.Message, err.Error(), log.String())
	})
	t.Run("a body that is not an answer", func(t *testing.T) {
		node := &eapiNode{answer: func(w http.ResponseWriter, _ *http.Request, cmds []string) {
			_, _ = w.Write([]byte("not JSON at all: " + strings.Join(cmds, "\n")))
		}}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "a body that is not a JSON-RPC answer") {
			t.Errorf("finding = %+v, want the body named and not quoted", f)
		}
		noContent(t, "an unreadable body", f.Message, err.Error(), log.String())
	})
	t.Run("an answer longer than the limit", func(t *testing.T) {
		// Cut at jsonRPCAnswerLimit, the answer no longer parses: reported as a body that
		// is not an answer and retried, never searched for a refusal.
		node := &eapiNode{answer: func(w http.ResponseWriter, _ *http.Request, _ []string) {
			_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":1,"result":[{"output":"`))
			_, _ = w.Write(bytes.Repeat([]byte("x"), jsonRPCAnswerLimit))
			_, _ = w.Write([]byte(`"}]}`))
		}}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "a body that is not a JSON-RPC answer") {
			t.Errorf("finding = %+v, want the cut answer named", f)
		}
		noContent(t, "a cut answer", f.Message, err.Error(), log.String())
	})
	t.Run("no result and no error", func(t *testing.T) {
		node := &eapiNode{answer: func(w http.ResponseWriter, _ *http.Request, _ []string) {
			_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":1}`))
		}}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "neither a result nor an error") {
			t.Errorf("finding = %+v, want the empty answer named", f)
		}
		noContent(t, "an empty answer", f.Message, err.Error(), log.String())
	})
	t.Run("the budget", func(t *testing.T) {
		node := &eapiNode{answer: func(_ http.ResponseWriter, r *http.Request, _ []string) {
			select {
			case <-r.Context().Done():
			case <-time.After(10 * time.Second):
			}
		}}
		a, in, _ := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		in.Push.TimeoutS = 1
		start := time.Now()
		_, _, err := pushOnce(t, a, in)
		if took := time.Since(start); took > 5*time.Second {
			t.Errorf("the push took %s against a 1s budget", took)
		}
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "within 1s (push_timeout_s)") || !strings.Contains(f.Message, eapiPath) {
			t.Errorf("finding = %+v, want the endpoint and the budget named", f)
		}
	})
	t.Run("a node that cannot be reached", func(t *testing.T) {
		a, in, log := eapiSetup(t, &eapiNode{answer: eapiRan}, psp.BootstrapViaStartupConfig)
		l, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			t.Fatal(err)
		}
		in.Push.Port = l.Addr().(*net.TCPAddr).Port
		_ = l.Close() // nothing listens there now
		_, _, err = pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "connection refused") {
			t.Errorf("finding = %+v, want the transport's error", f)
		}
		noContent(t, "a transport failure", f.Message, err.Error(), log.String())
	})
	t.Run("a push login unset", func(t *testing.T) {
		node := &eapiNode{answer: eapiRan}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		a.Getenv = mapEnv(map[string]string{"FYLGJA_EOS_USERNAME": "admin"})
		_, _, err := pushOnce(t, a, in)
		f := stepFailure(t, err, findings.RulePushFailed)
		if !strings.Contains(f.Message, "FYLGJA_EOS_PASSWORD is unset") || len(node.sent()) != 0 {
			t.Errorf("finding %+v after %d requests, want the variable named and nothing sent", f, len(node.sent()))
		}
		noContent(t, "an unset login", f.Message, err.Error(), log.String())
	})
}

// A cancellation reaches an eAPI push as it reaches a JSON-RPC one: a cancellation the
// workflow asked for is a cancellation, and a heartbeat that never reached the workflow
// service is push.failed, naming the artifact, and retried.
func TestPushEAPICutShort(t *testing.T) {
	node := &eapiNode{answer: func(_ http.ResponseWriter, r *http.Request, _ []string) { <-r.Context().Done() }}
	a, in, _ := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
	ctx, cancel := context.WithCancelCause(context.Background())
	time.AfterFunc(50*time.Millisecond, func() { cancel(temporal.NewCanceledError()) })

	_, err := a.PushConfig(ctx, in)
	var appErr *temporal.ApplicationError
	if !errors.Is(err, context.Canceled) || errors.As(err, &appErr) {
		t.Errorf("error %v, want the cancellation itself", err)
	}
}
