package lab

import (
	"bytes"
	"context"
	"crypto/md5"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"
	"unicode/utf8"

	"go.temporal.io/api/serviceerror"
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/converter"
	"go.temporal.io/sdk/temporal"

	"github.com/happypathnetworking/fylgja/internal/compiler"
	"github.com/happypathnetworking/fylgja/internal/findings"
	"github.com/happypathnetworking/fylgja/internal/lab/wire"
	"github.com/happypathnetworking/fylgja/internal/psp"
)

// pushMarker stands in for the configuration's own bytes: it must reach the node and
// nothing else — no finding, result, input or log line.
const pushMarker = "PUSH-TEST-MARKER"

// pushPassword is the login's value in these tests; like the marker, it reaches only the
// node's Authorization header.
const pushPassword = "push-test-password"

// pushArtifact is a small SR Linux artifact: a comment, an empty line (dropped), and a
// line SR Linux refuses, at line 10 of the file. The node counts
// commands, not file lines: `enter candidate private` is its line 1 and the empty line is
// not sent, so the refused line is the node's line 10 too, where without the empty line it
// would be 11: the node's line N is the file's line N−1.
const pushArtifact = "# n1: " + pushMarker + "\n" +
	"set / system name host-name n1\n" +
	"\n" +
	"set / interface ethernet-1/1 admin-state enable\n" +
	"set / interface ethernet-1/1 description \"to n2 ethernet-1/1\"\n" +
	"set / interface ethernet-1/1 subinterface 0 admin-state enable\n" +
	"set / interface ethernet-1/2 admin-state enable\n" +
	"set / interface ethernet-1/2 description \"to n3 ethernet-1/1\"\n" +
	"set / interface ethernet-1/2 subinterface 0 admin-state enable\n" +
	"set / interface e1-2 admin-state enable\n"

// pushNode is a fake SR Linux JSON-RPC endpoint: it keeps each request it is sent and
// answers with answer.
type pushNode struct {
	answer func(w http.ResponseWriter, r *http.Request, commands []string)

	mu       sync.Mutex
	commands [][]string
	logins   []string
}

func (n *pushNode) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var req jsonRPCRequest
	if r.URL.Path != "/jsonrpc" || r.Method != http.MethodPost || json.NewDecoder(r.Body).Decode(&req) != nil ||
		req.Method != "cli" || req.JSONRPC != "2.0" {
		http.Error(w, "not a JSON-RPC cli request", http.StatusBadRequest)
		return
	}
	u, p, _ := r.BasicAuth()
	n.mu.Lock()
	n.commands = append(n.commands, req.Params.Commands)
	n.logins = append(n.logins, u+":"+p)
	n.mu.Unlock()
	n.answer(w, r, req.Params.Commands)
}

func committed(w http.ResponseWriter, _ *http.Request, _ []string) {
	_, _ = io.WriteString(w, `{"jsonrpc":"2.0","id":1,"result":[{"text":"All changes have been committed. Leaving candidate mode.\n"}]}`)
}

// refusing answers as SR Linux answers a bad artifact: HTTP 200, a JSON-RPC error
// echoing every command before the node's reason.
func refusing(line int, reason string) func(http.ResponseWriter, *http.Request, []string) {
	return func(w http.ResponseWriter, _ *http.Request, commands []string) {
		msg := fmt.Sprintf("Error: Cli commands '%s' failed with error 1: At line %d: Error: %s",
			strings.Join(commands, "\n"), line, reason)
		_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{"code": -1, "message": msg}})
	}
}

// pushBootstrap is n1's bootstrap as the compiler renders one: a generated header, then
// the package's lines. Its own line numbers, so a refusal of one of them can be told from
// a refusal of the artifact's.
const pushBootstrap = "# generated by fylgja\n" +
	"\n" +
	"set / system name host-name n1\n" +
	"set / interface ethernet-1/1 admin-state enable\n"

// stagedBundle is the bundle one push reads, as the compiler wrote it and StageBundle
// copied it: a configuration artifact, a bootstrap, and how the bootstrap reaches the
// node. "startup_config" is M5's default and the shipped SR Linux package's, under which
// the bootstrap is the lab tool's business and the push sends the artifact alone; "push"
// is M7's, under which the push sends both.
type stagedBundle struct {
	artifact  string
	bootstrap string
	via       string
}

// stagePush writes that bundle under the activities' state root and returns the
// artifact's checksum, as the manifest records it.
func stagePush(t *testing.T, a *Activities, b stagedBundle) string {
	t.Helper()
	bundleDir := filepath.Join(a.Paths.Twin, "bundle")
	if err := os.MkdirAll(filepath.Join(bundleDir, "configs"), 0o755); err != nil {
		t.Fatal(err)
	}
	for name, content := range map[string]string{"n1.device-config": b.artifact, "n1.cli": b.bootstrap} {
		if err := os.WriteFile(filepath.Join(bundleDir, "configs", name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	sum := md5.Sum([]byte(b.artifact))
	checksum := hex.EncodeToString(sum[:])
	manifest := compiler.Manifest{
		BundleVersion: "3",
		Nodes: []compiler.ManifestNode{{
			Name: "n1", Platform: "testos", PSP: compiler.ManifestPSP{ID: "testos", Source: "embedded"},
			Artifact: &compiler.ManifestArtifact{
				Name: "device-config", ContentType: "text/plain", Checksum: checksum,
				Size: len(b.artifact), File: "configs/n1.device-config",
			},
			Bootstrap: compiler.ManifestBootstrap{File: "configs/n1.cli", Via: b.via},
		}},
	}
	raw, err := json.Marshal(manifest)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(bundleDir, compiler.ManifestFile), raw, 0o644); err != nil {
		t.Fatal(err)
	}
	return checksum
}

// pushNodeAt serves node over TLS and returns the host and port to reach it at, as a
// node's management address and its package's push port.
func pushNodeAt(t *testing.T, node http.Handler) (host string, port int) {
	t.Helper()
	srv := httptest.NewTLSServer(node)
	t.Cleanup(srv.Close)
	host, text, err := net.SplitHostPort(strings.TrimPrefix(srv.URL, "https://"))
	if err != nil {
		t.Fatal(err)
	}
	port, _ = strconv.Atoi(text)
	return host, port
}

// pushSetup stages pushArtifact as n1's under a fresh state root and serves node over TLS,
// returning the activities and the input that pushes it there.
func pushSetup(t *testing.T, node http.Handler) (*Activities, wire.PushInput, *bytes.Buffer) {
	t.Helper()
	a := testActivities(t, &fakeRunner{})
	a.Getenv = mapEnv(map[string]string{"FYLGJA_SRLINUX_USERNAME": "admin", "FYLGJA_SRLINUX_PASSWORD": pushPassword})
	var log bytes.Buffer
	a.Log = slog.New(slog.NewTextHandler(&log, &slog.HandlerOptions{Level: slog.LevelDebug}))

	checksum := stagePush(t, a, stagedBundle{artifact: pushArtifact, bootstrap: pushBootstrap, via: psp.BootstrapViaStartupConfig})
	host, port := pushNodeAt(t, node)
	push := srlinuxPush()
	push.Port = port
	return a, wire.PushInput{
		Node: "n1", MgmtIPv4: host, TwinDir: a.Paths.Twin, Artifact: "configs/n1.device-config",
		Checksum: checksum, Push: push,
	}, &log
}

// pushOnce runs PushConfig as the worker does, under the activity test environment, and
// counts its heartbeats.
func pushOnce(t *testing.T, a *Activities, in wire.PushInput) (wire.PushResult, int, error) {
	t.Helper()
	env := activityEnv(a.PushConfig, wire.ActPushConfig)
	var mu sync.Mutex
	beats := 0
	env.SetOnActivityHeartbeatListener(func(_ *activity.Info, _ converter.EncodedValues) {
		mu.Lock()
		beats++
		mu.Unlock()
	})
	val, err := env.ExecuteActivity(wire.ActPushConfig, in)
	mu.Lock()
	defer mu.Unlock()
	if err != nil {
		return wire.PushResult{}, beats, err
	}
	var res wire.PushResult
	if err := val.Get(&res); err != nil {
		t.Fatal(err)
	}
	return res, beats, nil
}

// artifactLines are pushArtifact's lines as they are sent: comments kept, empty dropped.
func artifactLines() []string {
	var out []string
	for _, l := range strings.Split(pushArtifact, "\n") {
		if l != "" {
			out = append(out, l)
		}
	}
	return out
}

// retryableFailure asserts err is a retryable push.failed and returns its finding.
func retryableFailure(t *testing.T, err error) findings.Finding {
	t.Helper()
	var appErr *temporal.ApplicationError
	if !errors.As(err, &appErr) || appErr.Type() != findings.RulePushFailed {
		t.Fatalf("error = %v, want an application error of type %s", err, findings.RulePushFailed)
	}
	if appErr.NonRetryable() {
		t.Errorf("%v is non-retryable; a push that could not be made is retried", err)
	}
	var f findings.Finding
	if err := appErr.Details(&f); err != nil {
		t.Fatal(err)
	}
	return f
}

// noContent fails if any of what surfaces carries the artifact's marker or the password.
func noContent(t *testing.T, what string, surfaces ...string) {
	t.Helper()
	for _, s := range surfaces {
		for _, secret := range []string{pushMarker, pushPassword} {
			if strings.Contains(s, secret) {
				t.Errorf("%s carries %q: %s", what, secret, s)
			}
		}
	}
}

// M5's push under merge: `enter candidate private`, the artifact's lines as they are with
// empty ones dropped, `commit now`, under the package's login, heartbeating before the
// request; the result names the checksum and size, and nothing that surfaces carries the
// content or the password. The shipped package is on
// replace from format 0.6 (TestPushConfigReplaceExplicit); a package on merge still
// creates.
func TestPushConfigMergeExplicit(t *testing.T) {
	node := &pushNode{answer: committed}
	a, in, log := pushSetup(t, node)
	in.Push.Mode = psp.ModeMerge

	res, beats, err := pushOnce(t, a, in)
	if err != nil {
		t.Fatal(err)
	}
	want := append(append([]string{"enter candidate private"}, artifactLines()...), "commit now")
	if len(node.commands) != 1 || !reflect.DeepEqual(node.commands[0], want) {
		t.Errorf("node was sent %q, want one request of %q", node.commands, want)
	}
	if node.logins[0] != "admin:"+pushPassword {
		t.Errorf("login = %q, want the package's variables' values", node.logins[0])
	}
	if res.Node != "n1" || res.Checksum != in.Checksum || res.Size != len(pushArtifact) || res.PushedInS <= 0 {
		t.Errorf("result = %+v, want n1 with the checksum, %d bytes and a duration", res, len(pushArtifact))
	}
	// A merge asks the node for no diff, so the result carries none, and its payload is
	// M5's byte for byte (diff is omitted when empty).
	if res.Diff != "" {
		t.Errorf("a merge's result carries a diff: %q", res.Diff)
	}
	if beats < 1 {
		t.Error("the push sent no heartbeat before its request")
	}

	b, err := json.Marshal(struct {
		In  wire.PushInput
		Res wire.PushResult
	}{in, res})
	if err != nil {
		t.Fatal(err)
	}
	noContent(t, "the push's input and result", string(b))
	noContent(t, "the push's log", log.String())
	for _, want := range []string{"pushed", "artifact=device-config", "checksum=" + in.Checksum,
		fmt.Sprintf("size=%d", len(pushArtifact)), `$FYLGJA_SRLINUX_USERNAME:$FYLGJA_SRLINUX_PASSWORD`} {
		if !strings.Contains(log.String(), want) {
			t.Errorf("log does not say %q:\n%s", want, log.String())
		}
	}
}

// Replace resets the candidate to the baseline, sends the bootstrap and the artifact, and
// asks for the diff before the commit; an implicit commit sends the
// lines alone. `delete /` is sent by no list (M5's replace, gone).
func TestPushConfigModes(t *testing.T) {
	replace := append([]string{"enter candidate private", "load startup"}, bootstrapCommands()...)
	replace = append(append(replace, artifactLines()...), "diff flat", "commit now")
	for _, c := range []struct {
		mode, commit string
		want         []string
	}{
		{"replace", "explicit", replace},
		{"merge", "implicit", artifactLines()},
	} {
		t.Run(c.mode+"/"+c.commit, func(t *testing.T) {
			node := &pushNode{answer: committed}
			a, in, _ := pushSetup(t, node)
			in.Push.Mode, in.Push.Commit = c.mode, c.commit
			if _, _, err := pushOnce(t, a, in); err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(node.commands[0], c.want) {
				t.Errorf("node was sent %q, want %q", node.commands[0], c.want)
			}
			for _, cmd := range node.commands[0] {
				if cmd == "delete /" {
					t.Error("the list sends `delete /`, M5's replace, which took the probe node dark")
				}
			}
		})
	}
	t.Run("replace/implicit", func(t *testing.T) {
		node := &pushNode{answer: committed}
		a, in, _ := pushSetup(t, node)
		in.Push.Mode, in.Push.Commit = "replace", "implicit"
		_, _, err := pushOnce(t, a, in)
		f := stepFailure(t, err, findings.RulePushFailed)
		const want = "mode replace with commit implicit has no command list for delivery json_rpc: " +
			"the reset loads the baseline into a candidate and commits it, which an implicit commit has none of"
		if !strings.Contains(f.Message, want) || len(node.commands) != 0 {
			t.Errorf("finding %+v after %d requests, want %q before any request", f, len(node.commands), want)
		}
	})
}

// bootstrapCommands are pushBootstrap's lines as they are sent: comments kept, empty
// dropped.
func bootstrapCommands() []string { return texts(configCommands([]byte(pushBootstrap), true)) }

// replaceDiff is a node's answer to a replace as SR Linux 24.7.1 gives it: the load's
// line, then the device's diff, then the commit's sentence, in one text entry. Its
// `insert` lines are configuration, which nothing but the push's result may carry.
const replaceDiff = "/system/configuration/checkpoint[id=__startup__]:\n" +
	"    Loaded startup configuration\n" +
	"\n" +
	"insert / interface ethernet-1/1 description \"to n2 ethernet-1/1\"\n" +
	"insert / system name host-name n1\n" +
	"All changes have been committed. Leaving candidate mode.\n"

// committedWithDiff answers a replace as SR Linux does, with no output-format: one
// result entry holding every command's text output.
func committedWithDiff(w http.ResponseWriter, _ *http.Request, _ []string) {
	_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "result": []map[string]string{{"text": replaceDiff}}})
}

// The push under replace, the shipped package's from format 0.6 (M11 D-033): one request of
// `enter candidate private`, `load
// startup`, the bootstrap's lines whatever bootstrap_via says, the
// artifact's, `diff flat` and `commit now`, with no output-format. The result carries the
// node's text output as the device's diff, and the log carries its length alone: no log
// line, finding or other field holds a line of it.
func TestPushConfigReplaceExplicit(t *testing.T) {
	for _, via := range []string{psp.BootstrapViaStartupConfig, psp.BootstrapViaPush} {
		t.Run(via, func(t *testing.T) {
			node := &pushNode{answer: committedWithDiff}
			a, in, log := pushSetup(t, node)
			stagePush(t, a, stagedBundle{artifact: pushArtifact, bootstrap: pushBootstrap, via: via})
			in.Push.Mode = psp.ModeReplace

			res, _, err := pushOnce(t, a, in)
			if err != nil {
				t.Fatal(err)
			}
			want := append([]string{cmdEnterCandidate, cmdLoadStartup}, bootstrapCommands()...)
			want = append(append(want, artifactLines()...), cmdDiffFlat, cmdCommitNow)
			if len(node.commands) != 1 || !reflect.DeepEqual(node.commands[0], want) {
				t.Errorf("node was sent %q,\nwant one request of %q", node.commands, want)
			}
			if res.Diff != replaceDiff {
				t.Errorf("result diff = %q, want the node's text output %q", res.Diff, replaceDiff)
			}
			if res.Node != "n1" || res.Checksum != in.Checksum || res.Size != len(pushArtifact) {
				t.Errorf("result = %+v, want n1 with the artifact's checksum and size", res)
			}

			// The diff is the result's alone: the log names its length, and no line of it.
			if !strings.Contains(log.String(), fmt.Sprintf("diff_bytes=%d", len(replaceDiff))) {
				t.Errorf("the log does not name the diff's length:\n%s", log.String())
			}
			for _, line := range []string{"insert / interface", "insert / system", "Loaded startup configuration"} {
				if strings.Contains(log.String(), line) {
					t.Errorf("the log carries the diff's %q:\n%s", line, log.String())
				}
			}
			noContent(t, "the push's log", log.String())
			// The by_hand line sends the replace, bootstrap file first; its
			// whole text is TestPushByHandFollowsTheMode's.
			files := []string{filepath.Join(a.Paths.Twin, "bundle", "configs", "n1.cli"),
				filepath.Join(a.Paths.Twin, "bundle", "configs", "n1.device-config")}
			for _, want := range []string{cmdLoadStartup, cmdDiffFlat, strings.Join(files, " ")} {
				if !strings.Contains(log.String(), want) {
					t.Errorf("the by_hand line does not carry %q:\n%s", want, log.String())
				}
			}
		})
	}
}

// The push as an operator repeats it by hand follows the mode's list, so a push repeated
// under replace resets and asks for the diff as the activity does; it names the login by
// its variables and the files by their staged paths, bootstrap first.
func TestPushByHandFollowsTheMode(t *testing.T) {
	files := []string{"/twin/bundle/configs/n1.cli", "/twin/bundle/configs/n1.device-config"}
	base := wire.PushInput{Node: "n1", MgmtIPv4: "172.20.20.2"}
	for _, c := range []struct {
		name string
		push wire.PushSpec
		want string
	}{
		{"json_rpc replace", func() wire.PushSpec { p := srlinuxPush(); p.Mode = psp.ModeReplace; return p }(),
			`jq -Rs '{jsonrpc:"2.0",id:1,method:"cli",params:{commands:(["enter candidate private","load startup"]+(split("\n")|map(select(test("\\S"))))+["diff flat","commit now"])}}' ` +
				`/twin/bundle/configs/n1.cli /twin/bundle/configs/n1.device-config | curl -sk -u "$FYLGJA_SRLINUX_USERNAME:$FYLGJA_SRLINUX_PASSWORD" https://172.20.20.2:443/jsonrpc -d @-`},
		{"json_rpc merge", func() wire.PushSpec { p := srlinuxPush(); p.Mode = psp.ModeMerge; return p }(),
			`jq -Rs '{jsonrpc:"2.0",id:1,method:"cli",params:{commands:(["enter candidate private"]+(split("\n")|map(select(test("\\S"))))+["commit now"])}}' ` +
				`/twin/bundle/configs/n1.cli /twin/bundle/configs/n1.device-config | curl -sk -u "$FYLGJA_SRLINUX_USERNAME:$FYLGJA_SRLINUX_PASSWORD" https://172.20.20.2:443/jsonrpc -d @-`},
		{"eapi replace", func() wire.PushSpec { p := eapiPush(); p.Mode = psp.ModeReplace; return p }(),
			`jq -Rs '{jsonrpc:"2.0",id:1,method:"runCmds",params:{version:1,cmds:(["enable","configure session by-hand","rollback clean-config","copy startup-config session-config"]+(split("\n")|map(select(test("\\S"))))+["show session-config diffs","commit"]),format:"text"}}' ` +
				`/twin/bundle/configs/n1.cli /twin/bundle/configs/n1.device-config | curl -sk -u "$FYLGJA_EOS_USERNAME:$FYLGJA_EOS_PASSWORD" https://172.20.20.2:443/command-api -d @-`},
		{"eapi merge", eapiPush(),
			`jq -Rs '{jsonrpc:"2.0",id:1,method:"runCmds",params:{version:1,cmds:(["enable","configure session by-hand"]+(split("\n")|map(select(test("\\S"))))+["commit"]),format:"json"}}' ` +
				`/twin/bundle/configs/n1.cli /twin/bundle/configs/n1.device-config | curl -sk -u "$FYLGJA_EOS_USERNAME:$FYLGJA_EOS_PASSWORD" https://172.20.20.2:443/command-api -d @-`},
	} {
		t.Run(c.name, func(t *testing.T) {
			in := base
			in.Push = c.push
			if got := pushByHand(in, files); got != c.want {
				t.Errorf("by hand:\n got  %s\n want %s", got, c.want)
			}
		})
	}
}

// A diff longer than DiffLimit is cut there, at a character boundary, and closed with a
// note, so the activity's result stays under the workflow service's payload limit. The
// log still names the length the device answered.
func TestPushConfigCutsALongDiff(t *testing.T) {
	const line = "insert / interface ethernet-1/1 description \"é\"\n"
	// The diff opens with as many bytes as put byte DiffLimit on é's second byte, so a cut
	// that did not back off to a character boundary would end inside it.
	head := (DiffLimit - strings.Index(line, "é") - 1) % len(line)
	long := strings.Repeat("x", head) + strings.Repeat(line, DiffLimit/40)
	if len(long) <= DiffLimit || utf8.RuneStart(long[DiffLimit]) {
		t.Fatalf("the test's diff is %d bytes with byte %d starting a character; want more bytes, and the cut inside é",
			len(long), DiffLimit)
	}
	node := &pushNode{answer: func(w http.ResponseWriter, _ *http.Request, _ []string) {
		_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "result": []map[string]string{{"text": long}}})
	}}
	a, in, log := pushSetup(t, node)
	in.Push.Mode = psp.ModeReplace
	res, _, err := pushOnce(t, a, in)
	if err != nil {
		t.Fatal(err)
	}
	kept, ok := strings.CutSuffix(res.Diff, diffCutNote)
	if !ok || len(kept) > DiffLimit || !strings.HasPrefix(long, kept) || !utf8.ValidString(res.Diff) {
		t.Errorf("result diff is %d bytes ending %q; want at most %d of the device's bytes, whole characters, then %q",
			len(res.Diff), res.Diff[max(0, len(res.Diff)-40):], DiffLimit, diffCutNote)
	}
	if !strings.Contains(log.String(), fmt.Sprintf("diff_bytes=%d", len(long))) {
		t.Errorf("the log does not name the length the device answered:\n%s", log.String())
	}
}

// A replace the node refuses at its commit answers with the reason, an empty line, and
// the request's output so far, `diff flat`'s lines included (SR Linux 24.7.1's message,
// the reason verbatim). The refusal keeps the reason alone: nothing from the empty line on, and no
// line of configuration.
func TestPushConfigReplaceRefusedAtCommit(t *testing.T) {
	const reason = "Error in path: .interface{.name==\"ethernet-1/99\"}\n    [InvalidArgument] invalid port 99, max is 58"
	const after = "/system/configuration/checkpoint[id=__startup__]:\n    Loaded startup configuration\n\n" +
		"insert / interface ethernet-1/1 description probe-C\ninsert / interface ethernet-1/99 admin-state enable"
	node := &pushNode{answer: func(w http.ResponseWriter, r *http.Request, commands []string) {
		// The node counts the command list; `commit now` is its last.
		refusing(len(commands), reason+"\n\n"+after)(w, r, commands)
	}}
	a, in, log := pushSetup(t, node)
	in.Push.Mode = psp.ModeReplace

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at its `commit now`: %s", in.Checksum, reason)
	if f.Message != want {
		t.Errorf("finding message = %q\nwant %q", f.Message, want)
	}
	if !strings.Contains(f.Message, "invalid port 99, max is 58") {
		t.Errorf("the refusal does not name the node's reason: %s", f.Message)
	}
	for _, surface := range []string{f.Message, err.Error(), log.String()} {
		for _, line := range []string{"insert /", "delete /", "update /", "replace /", "Loaded startup configuration"} {
			if strings.Contains(surface, line) {
				t.Errorf("the refusal carries %q: %s", line, surface)
			}
		}
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
}

// A replace refused with the marker but without `At line N:` names no line, and its
// reason is cut as the line-numbered shape's is: up to the first empty line, without the
// diff behind it or any diff line inside it.
func TestPushConfigReplaceRefusedWithoutALine(t *testing.T) {
	const reason = "Error: commit failed: invalid port 99, max is 58"
	const diff = "insert / interface ethernet-1/99 admin-state enable\ndelete / interface ethernet-1/2 description"
	node := &pushNode{answer: func(w http.ResponseWriter, _ *http.Request, commands []string) {
		msg := fmt.Sprintf("Error: Cli commands '%s' failed with error 1: %s\nupdate / interface ethernet-1/1 description probe-C\n\n%s",
			strings.Join(commands, "\n"), reason, diff)
		_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{"code": -1, "message": msg}})
	}}
	a, in, log := pushSetup(t, node)
	in.Push.Mode = psp.ModeReplace

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s): %s", in.Checksum, reason)
	if f.Message != want {
		t.Errorf("finding message = %q\nwant %q", f.Message, want)
	}
	for _, surface := range []string{f.Message, err.Error(), log.String()} {
		for _, line := range []string{"insert /", "delete /", "update /", "replace /"} {
			if strings.Contains(surface, line) {
				t.Errorf("the refusal carries %q: %s", line, surface)
			}
		}
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
}

// A replace refused at its commit whose diff carries the marker itself, in a value of the
// configuration, is read at the marker that ends the echo: the reason and the command are
// the node's, and nothing of the diff reaches the finding, the error or the log
// (Constitution X). The echo ends at the first line
// that is blank once trimmed, as the reason does (reasonOnly), so a separator line of
// spaces or one ending "\r\n" ends it too.
func TestPushConfigReplaceRefusedWithTheMarkerInItsDiff(t *testing.T) {
	const reason = "invalid port 99, max is 58"
	const diff = `insert / interface ethernet-1/1 description "core' failed with error 1: At line 2: Error: SECRET-DESC"`
	for _, c := range []struct{ name, separator string }{
		{"an empty line", "\n"},
		{"a line blank once trimmed", " \r\n"},
	} {
		t.Run(c.name, func(t *testing.T) {
			node := &pushNode{answer: func(w http.ResponseWriter, _ *http.Request, commands []string) {
				msg := fmt.Sprintf("Error: Cli commands '%s' failed with error 5: At line %d: Error: %s\n%s%s",
					strings.Join(commands, "\n"), len(commands), reason, c.separator, diff)
				_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{"code": -1, "message": msg}})
			}}
			a, in, log := pushSetup(t, node)
			in.Push.Mode = psp.ModeReplace

			_, _, err := pushOnce(t, a, in)
			f := stepFailure(t, err, findings.RulePushRefused)
			want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at its `commit now`: %s", in.Checksum, reason)
			if f.Message != want {
				t.Errorf("finding message = %q\nwant %q", f.Message, want)
			}
			for _, surface := range []string{f.Message, err.Error(), log.String()} {
				for _, fragment := range []string{"SECRET-DESC", `"core`, "insert /", "At line 2"} {
					if strings.Contains(surface, fragment) {
						t.Errorf("the refusal carries %q of the diff: %s", fragment, surface)
					}
				}
			}
			noContent(t, "the refusal", f.Message, err.Error(), log.String())
		})
	}
}

// cutInsideEcho answers as SR Linux 24.7.1 answered a refused replace: a JSON-RPC error
// whose message the node cut at about 1 KiB, inside its echo of the
// commands, ending "...". Neither the marker that ends the echo nor the reason arrives.
// The echo here is shorter than the node's cap, so it is cut at two thirds of its length,
// which leaves the artifact's first line, and the test marker, inside what is sent.
func cutInsideEcho(w http.ResponseWriter, _ *http.Request, commands []string) {
	msg := "Error: Cli commands '" + strings.Join(commands, "\n")
	msg = msg[:len(msg)*2/3] + "..."
	_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{"code": -1, "message": msg}})
}

// validateCommands is the request a refused replace whose reason was cut is asked again
// with (D-034): it enters the private candidate the refusal left and validates it.
var validateCommands = []string{cmdEnterCandidate, cmdCommitValidate}

// askedAgain answers the replace with first and the request that asks again with second.
func askedAgain(first, second func(http.ResponseWriter, *http.Request, []string)) func(http.ResponseWriter, *http.Request, []string) {
	return func(w http.ResponseWriter, r *http.Request, commands []string) {
		if reflect.DeepEqual(commands, validateCommands) {
			second(w, r, commands)
			return
		}
		first(w, r, commands)
	}
}

// withheldSentence is the refusal's wording when the node's message gives no reason
// Fylgja can read.
const withheldSentence = "the node's message is not of the shape Fylgja strips the echoed commands from, so it is withheld"

// validatesSentence and notGivenAgainSentence are a refused replace's wording when neither
// its request nor the `commit validate` after it gave a reason (D-035), spelled out here
// so a change to either is a change to the contract.
const (
	validatesSentence     = "the node's message ends before any reason Fylgja can read, and the candidate it refused passes `commit validate`, which does not run every check a commit does (D-035)"
	notGivenAgainSentence = "the node's message ends before any reason Fylgja can read, and asking again with `commit validate` gave none (D-035)"
)

// validateRefusal answers `enter candidate private`, `commit validate` as SR Linux 24.7.1
// answered it live for a candidate holding a VLAN encapsulation on a port without
// vlan-tagging, verbatim but for the echo, which is the two
// commands it was sent: the reason at line 2, then the node's own "Validate failed".
func validateRefusal(w http.ResponseWriter, _ *http.Request, commands []string) {
	msg := "Error: Cli commands '" + strings.Join(commands, "\n") + "' failed with error 1: At line 2: " + validateReason + "\n"
	_ = json.NewEncoder(w).Encode(map[string]any{"jsonrpc": "2.0", "id": 1, "error": map[string]any{"code": -1, "message": msg}})
}

const validateReason = "Error in /interface[name=ethernet-1/5]/subinterface[index=5]/vlan/encap/single-tagged/vlan-id::\n" +
	"    vlan-id only configurable if vlan-tagging enabled on parent interface\nError: Validate failed"

// A replace whose refusal the node cut before its reason is asked again, by `enter
// candidate private`, `commit validate`, which commits nothing; the reason that answer
// gives is the finding's, re-based on its own two commands, and nothing of either echo or
// of any diff line reaches the finding, the error or the log (D-034).
// The answer is the node's own, for a constraint `commit validate` checks; a port out of
// range it does not check, and that case is TestPushConfigReplaceRefusalCutAndNotGivenAgain's
// "the candidate validates".
func TestPushConfigReplaceRefusalCutIsAskedAgain(t *testing.T) {
	const reason = validateReason
	node := &pushNode{answer: askedAgain(cutInsideEcho, validateRefusal)}
	a, in, log := pushSetup(t, node)
	in.Push.Mode = psp.ModeReplace

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at its `commit validate`: %s", in.Checksum, reason)
	if f.Message != want {
		t.Errorf("finding message = %q\nwant %q", f.Message, want)
	}
	if len(node.commands) != 2 || !reflect.DeepEqual(node.commands[1], validateCommands) {
		t.Fatalf("node was sent %q, want the replace and then exactly %q", node.commands, validateCommands)
	}
	for _, surface := range []string{f.Message, err.Error(), log.String()} {
		for _, line := range []string{"insert /", "delete /", "update /", "replace /", "Loaded startup configuration"} {
			if strings.Contains(surface, line) {
				t.Errorf("the refusal carries %q: %s", line, surface)
			}
		}
	}
	if !strings.Contains(log.String(), "asked for and given") {
		t.Errorf("the log does not say the reason was asked for and given:\n%s", log.String())
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
}

// When asking again gives no reason either, the refusal says which of D-035's two
// sentences applies: the candidate validates (a check the node makes only as a commit
// applies, or a refusal at parse time), or the second answer is cut too, the node fails
// the request, or it never answers within the push's budget. Each is still push.refused,
// final: a request made after the node refused cannot turn the refusal into a failure
// that is retried (D-034).
func TestPushConfigReplaceRefusalCutAndNotGivenAgain(t *testing.T) {
	for _, c := range []struct {
		name   string
		second func(http.ResponseWriter, *http.Request, []string)
		log    string
		reason string
	}{
		// SR Linux 24.7.1's answer, verbatim, for a candidate holding a port out of range,
		// which it checks only as a commit applies.
		{"the candidate validates", func(w http.ResponseWriter, _ *http.Request, _ []string) {
			_, _ = io.WriteString(w, `{"result":[{"text":"All changes are valid.\n"}],"id":1,"jsonrpc":"2.0"}`)
		}, "candidate validates", validatesSentence},
		{"the second answer is cut too", cutInsideEcho, "asked for and not given", notGivenAgainSentence},
		{"the node fails the request", func(w http.ResponseWriter, _ *http.Request, _ []string) {
			http.Error(w, "busy "+pushMarker, http.StatusServiceUnavailable)
		}, "could not be asked for", notGivenAgainSentence},
		{"the node never answers within the budget", func(_ http.ResponseWriter, r *http.Request, _ []string) {
			select {
			case <-r.Context().Done():
			case <-time.After(10 * time.Second):
			}
		}, "could not be asked for", notGivenAgainSentence},
	} {
		t.Run(c.name, func(t *testing.T) {
			node := &pushNode{answer: askedAgain(cutInsideEcho, c.second)}
			a, in, log := pushSetup(t, node)
			in.Push.Mode = psp.ModeReplace
			in.Push.TimeoutS = 1

			_, _, err := pushOnce(t, a, in)
			f := stepFailure(t, err, findings.RulePushRefused)
			want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s): %s", in.Checksum, c.reason)
			if f.Message != want {
				t.Errorf("finding message = %q\nwant %q", f.Message, want)
			}
			if len(node.commands) != 2 || !reflect.DeepEqual(node.commands[1], validateCommands) {
				t.Fatalf("node was sent %q, want the replace and then exactly %q", node.commands, validateCommands)
			}
			if !strings.Contains(log.String(), c.log) {
				t.Errorf("the log does not say %q:\n%s", c.log, log.String())
			}
			noContent(t, "the refusal", f.Message, err.Error(), log.String())
		})
	}
}

// The node is asked again only for a replace whose refusal gave no reason: a reason that
// fits is the finding's from the one request, and a merge, M5's push, is M5's whatever
// its refusal says (D-034 is the replace's).
func TestPushConfigAsksAgainOnlyForAReplaceWithNoReason(t *testing.T) {
	for _, c := range []struct {
		name   string
		mode   string
		answer func(http.ResponseWriter, *http.Request, []string)
		where  string
	}{
		{"a replace whose reason fits", psp.ModeReplace, func(w http.ResponseWriter, r *http.Request, commands []string) {
			refusing(len(commands), "invalid port 99, max is 58")(w, r, commands)
		}, " at its `commit now`: invalid port 99, max is 58"},
		{"a merge whose reason was cut", psp.ModeMerge, cutInsideEcho, ": " + withheldSentence},
	} {
		t.Run(c.name, func(t *testing.T) {
			node := &pushNode{answer: c.answer}
			a, in, _ := pushSetup(t, node)
			in.Push.Mode = c.mode

			_, _, err := pushOnce(t, a, in)
			f := stepFailure(t, err, findings.RulePushRefused)
			if want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s)%s", in.Checksum, c.where); f.Message != want {
				t.Errorf("finding message = %q\nwant %q", f.Message, want)
			}
			if len(node.commands) != 1 {
				t.Errorf("node was sent %d requests, want the push alone: %q", len(node.commands), node.commands)
			}
		})
	}
}

// The reason ends at its first empty line, and a line of it that reads as a diff line is
// dropped even before one: each is configuration the node quoted.
func TestReasonOnlyKeepsTheReason(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"invalid port 99, max is 58", "invalid port 99, max is 58"},
		{"invalid port 99\n\ninsert / interface ethernet-1/99", "invalid port 99"},
		{"invalid port 99\n  \nanything after a blank line", "invalid port 99"},
		{"invalid port 99\ninsert / a\n  delete / b\nupdate / c\nreplace / d\nthe rest", "invalid port 99\nthe rest"},
		{"\n\ninsert / a", ""},
	} {
		if got := reasonOnly(c.in); got != c.want {
			t.Errorf("reasonOnly(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// A refused line is push.refused, final, naming the node, the artifact, its checksum, the
// artifact's own line and the node's reason — and none of the commands the node echoed.
// The line is re-based through the command list, so a dropped empty line is counted: the
// node's line 10 here, the file's line 10.
//
// The list is M5's merge list, whose line numbers the node's count re-bases through; the
// replace's refusal is TestPushConfigReplaceRefusedAtCommit.
func TestPushConfigRefusedLine(t *testing.T) {
	const reason = `Failed to parse value 'e1-2' for key 'name' (node 'interface') - Invalid value "e1-2": Must match the pattern '(mgm…`
	node := &pushNode{answer: refusing(10, reason)}
	a, in, log := pushSetup(t, node)
	in.Push.Mode = psp.ModeMerge

	_, _, err := pushOnce(t, a, in)
	f := stepFailure(t, err, findings.RulePushRefused)
	want := fmt.Sprintf("node n1 refused artifact device-config (checksum %s) at line 10: %s", in.Checksum, reason)
	if f.Message != want || f.Step != findings.StepPush || f.Object != "n1" {
		t.Errorf("finding = %+v\nwant message %q at step push on n1", f, want)
	}
	noContent(t, "the refusal", f.Message, err.Error(), log.String())
	// The node echoed every command it was sent, framing and artifact alike; the refusal
	// keeps its reason and drops the echo, line by line. The refused line itself is
	// named by number, never quoted.
	for _, c := range append([]string{"enter candidate private", "commit now"}, artifactLines()...) {
		if strings.Contains(f.Message, c) || strings.Contains(err.Error(), c) {
			t.Errorf("the refusal carries the echoed command %q: %s", c, f.Message)
		}
	}
}

// The push's wire types name the staged file and its identity, never its bytes (Constitution
// VIII: paths and identities cross the queue, content does not). The field sets are
// pinned, so a field added to either — a content field, or any other — fails here until
// it is shown to be a path or an identity and added to this list.
func TestPushWireCarriesNoContent(t *testing.T) {
	for _, c := range []struct {
		v    any
		want []string
	}{
		{wire.PushInput{}, []string{"node", "mgmt_ipv4", "twin_dir", "artifact", "checksum", "push"}},
		// M11: diff is the device's own account of a replace, the push activity's result
		// and its only home. The workflow
		// strips it before any other input or result is built, and it is a string, never
		// a list or bytes.
		{wire.PushResult{}, []string{"node", "pushed_in_s", "checksum", "size", "diff"}},
		{wire.PushSpec{}, []string{"delivery", "mode", "commit", "scheme", "port", "username_env", "password_env", "timeout_s"}},
	} {
		typ := reflect.TypeOf(c.v)
		var got []string
		for i := range typ.NumField() {
			f := typ.Field(i)
			got = append(got, strings.Split(f.Tag.Get("json"), ",")[0])
			if f.Type.Kind() == reflect.Slice || f.Type.Kind() == reflect.Map {
				t.Errorf("%s.%s is a %s: a list or bytes on the queue", typ.Name(), f.Name, f.Type)
			}
		}
		if !reflect.DeepEqual(got, c.want) {
			t.Errorf("%s carries %v, want exactly %v", typ.Name(), got, c.want)
		}
	}
}

// Where the node names a framing command, or says nothing Fylgja can read, the refusal
// says so and withholds the message whole.
func TestRefusalFromFramingAndUnknownShapes(t *testing.T) {
	cmds, err := jsonRPCCommands(pushBody{artifact: []byte(pushArtifact)}, "merge", "explicit")
	if err != nil {
		t.Fatal(err)
	}
	commit := refusalFrom(fmt.Sprintf("Error: Cli commands '%s' failed with error 1: At line %d: Error: validation failed",
		strings.Join(texts(cmds), "\n"), len(cmds)), cmds)
	if commit.where() != " at its `commit now`" || commit.reason != "validation failed" {
		t.Errorf("refusal = %+v, want the commit named", commit)
	}
	unknown := refusalFrom("something else entirely: "+pushMarker, cmds)
	noContent(t, "an unknown refusal", unknown.Error())

	// The only marker comes after the first empty line, in what the node output, not at
	// the end of its echo, which was cut short: it cannot be placed.
	late := refusalFrom("Error: Cli commands '"+strings.Join(texts(cmds), "\n")[:20]+"...\n\n"+
		`insert / interface ethernet-1/1 description "`+pushMarker+`' failed with error 1: At line 2: Error: SECRET-DESC"`, cmds)
	if !late.withheld || strings.Contains(late.Error(), "SECRET-DESC") {
		t.Errorf("refusal = %+v, want the message withheld whole", late)
	}
	noContent(t, "a refusal whose marker is in the output", late.Error())
}

// A status that is not 2xx and a node that cannot be reached are push.failed and retried;
// neither quotes the node's body, which would echo the artifact.
func TestPushConfigFailures(t *testing.T) {
	t.Run("500", func(t *testing.T) {
		node := &pushNode{answer: func(w http.ResponseWriter, _ *http.Request, commands []string) {
			http.Error(w, strings.Join(commands, "\n"), http.StatusInternalServerError)
		}}
		a, in, log := pushSetup(t, node)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "500") || f.Step != findings.StepPush || f.Object != "n1" {
			t.Errorf("finding = %+v, want the status at step push on n1", f)
		}
		noContent(t, "a 500", f.Message, log.String())
	})
	t.Run("401", func(t *testing.T) {
		node := &pushNode{answer: func(w http.ResponseWriter, _ *http.Request, _ []string) {
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
		}}
		a, in, log := pushSetup(t, node)
		_, _, err := pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "401") || !strings.Contains(f.Message, "FYLGJA_SRLINUX_USERNAME/FYLGJA_SRLINUX_PASSWORD") {
			t.Errorf("finding = %+v, want the status and the login's variable names", f)
		}
		noContent(t, "a 401", f.Message, err.Error(), log.String())
	})
	t.Run("transport", func(t *testing.T) {
		a, in, log := pushSetup(t, &pushNode{answer: committed})
		l, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			t.Fatal(err)
		}
		in.Push.Port = l.Addr().(*net.TCPAddr).Port
		_ = l.Close() // nothing listens there now
		_, _, err = pushOnce(t, a, in)
		f := retryableFailure(t, err)
		if !strings.Contains(f.Message, "connection refused") {
			t.Errorf("finding = %+v, want the transport's error", f)
		}
		noContent(t, "a transport failure", f.Message, err.Error(), log.String())
	})
	t.Run("a staged file changed after staging", func(t *testing.T) {
		node := &pushNode{answer: committed}
		a, in, log := pushSetup(t, node)
		in.Checksum = strings.Repeat("0", 32)
		_, _, err := pushOnce(t, a, in)
		f := stepFailure(t, err, findings.RulePushFailed)
		if !strings.Contains(f.Message, "changed after staging") || len(node.commands) != 0 {
			t.Errorf("finding %+v after %d requests, want the mismatch named and nothing sent", f, len(node.commands))
		}
		noContent(t, "a changed staged file", f.Message, err.Error(), log.String())
	})
	t.Run("a push login unset", func(t *testing.T) {
		node := &pushNode{answer: committed}
		a, in, log := pushSetup(t, node)
		a.Getenv = mapEnv(map[string]string{"FYLGJA_SRLINUX_USERNAME": "admin"})
		_, _, err := pushOnce(t, a, in)
		f := stepFailure(t, err, findings.RulePushFailed)
		if !strings.Contains(f.Message, "FYLGJA_SRLINUX_PASSWORD is unset") || len(node.commands) != 0 {
			t.Errorf("finding %+v after %d requests, want the variable named and nothing sent", f, len(node.commands))
		}
		noContent(t, "an unset login", f.Message, err.Error(), log.String())
	})
}

// A node that does not answer is cut off at the package's push_timeout_s, not the
// activity's start-to-close, and the failure is retried.
func TestPushConfigHonoursTheBudget(t *testing.T) {
	node := &pushNode{answer: func(_ http.ResponseWriter, r *http.Request, _ []string) {
		select {
		case <-r.Context().Done():
		case <-time.After(10 * time.Second):
		}
	}}
	a, in, _ := pushSetup(t, node)
	in.Push.TimeoutS = 1
	start := time.Now()
	_, _, err := pushOnce(t, a, in)
	if took := time.Since(start); took > 5*time.Second {
		t.Errorf("the push took %s against a 1s budget", took)
	}
	f := retryableFailure(t, err)
	if !strings.Contains(f.Message, "within 1s (push_timeout_s)") {
		t.Errorf("finding = %+v, want the budget named", f)
	}
}

// A cancellation the workflow asked for is a cancellation; a heartbeat that did not reach
// the workflow service is named under push.failed, with the artifact the node was taking,
// and retried, as M2 names a deploy cut short.
func TestPushConfigCutShort(t *testing.T) {
	for _, c := range []struct {
		name  string
		cause error
		lost  bool
	}{
		{"a cancellation the workflow asked for", temporal.NewCanceledError(), false},
		{"a heartbeat that did not reach the service", serviceerror.NewDeadlineExceeded("context deadline exceeded"), true},
	} {
		t.Run(c.name, func(t *testing.T) {
			node := &pushNode{answer: func(_ http.ResponseWriter, r *http.Request, _ []string) { <-r.Context().Done() }}
			a, in, _ := pushSetup(t, node)
			ctx, cancel := context.WithCancelCause(context.Background())
			time.AfterFunc(50*time.Millisecond, func() { cancel(c.cause) })

			_, err := a.PushConfig(ctx, in)
			if !c.lost {
				var appErr *temporal.ApplicationError
				if !errors.Is(err, context.Canceled) || errors.As(err, &appErr) {
					t.Errorf("error %v, want the cancellation itself", err)
				}
				return
			}
			var appErr *temporal.ApplicationError
			if !errors.As(err, &appErr) || appErr.Type() != HeartbeatLostType || appErr.NonRetryable() {
				t.Fatalf("error %v, want a retryable %s", err, HeartbeatLostType)
			}
			var f findings.Finding
			if err := appErr.Details(&f); err != nil {
				t.Fatal(err)
			}
			// Every push.failed names the artifact and checksum the node was taking, the
			// lost heartbeat's too.
			cut := "the push of artifact device-config (checksum " + in.Checksum + ") to n1 was cut short"
			if f.Rule != findings.RulePushFailed || f.Step != findings.StepPush || f.Object != "n1" ||
				!strings.Contains(f.Message, cut) {
				t.Errorf("finding = %+v, want push.failed at step push saying %q", f, cut)
			}
		})
	}
}

// The dispatch sends by the mechanism the package's delivery names, and by no other: a
// json_rpc node is reached at its JSON-RPC endpoint with M5's command list, an eapi node
// at its command API with M7's, and a delivery this build has no mechanism for is refused
// before anything is sent, naming both it does have.
func TestPushConfigDispatchesOnTheDelivery(t *testing.T) {
	t.Run("json_rpc", func(t *testing.T) {
		node := &pushNode{answer: committed}
		a, in, log := pushSetup(t, node)
		in.Push.Mode = psp.ModeMerge
		if _, _, err := pushOnce(t, a, in); err != nil {
			t.Fatal(err)
		}
		want := append(append([]string{cmdEnterCandidate}, artifactLines()...), cmdCommitNow)
		if len(node.commands) != 1 || !reflect.DeepEqual(node.commands[0], want) {
			t.Errorf("node was sent %q, want one request of %q", node.commands, want)
		}
		if !strings.Contains(log.String(), "delivery="+DeliveryJSONRPC) || !strings.Contains(log.String(), "/jsonrpc") {
			t.Errorf("the log does not name the mechanism and its endpoint:\n%s", log.String())
		}
	})

	t.Run("eapi", func(t *testing.T) {
		node := &eapiNode{answer: eapiRan}
		a, in, log := eapiSetup(t, node, psp.BootstrapViaStartupConfig)
		if _, _, err := pushOnce(t, a, in); err != nil {
			t.Fatal(err)
		}
		sent := node.sent()
		want := append(append([]string{cmdEnable, cmdSession + sessionName(sent[0])}, eapiLines()...), cmdCommit)
		if len(sent) != 1 || !reflect.DeepEqual(sent[0], want) {
			t.Errorf("node was sent %q, want one request of %q", sent, want)
		}
		if !strings.Contains(log.String(), "delivery="+DeliveryEAPI) || !strings.Contains(log.String(), eapiPath) {
			t.Errorf("the log does not name the mechanism and its endpoint:\n%s", log.String())
		}
	})

	t.Run("a delivery with no mechanism", func(t *testing.T) {
		node := &pushNode{answer: committed}
		a, in, log := pushSetup(t, node)
		in.Push.Delivery = "netconf"
		_, _, err := pushOnce(t, a, in)
		f := stepFailure(t, err, findings.RulePushFailed)
		want := fmt.Sprintf("delivery %q is not a mechanism this build pushes by (only %s and %s are)", "netconf", DeliveryJSONRPC, DeliveryEAPI)
		if !strings.Contains(f.Message, want) || len(node.commands) != 0 {
			t.Errorf("finding %+v after %d requests, want %q and nothing sent", f, len(node.commands), want)
		}
		noContent(t, "an unknown delivery", f.Message, err.Error(), log.String())
	})
}

// Whether the bootstrap goes through the push is the staged manifest's answer, not the
// delivery's: the json_rpc mechanism sends it too, inside the
// candidate ahead of the artifact's lines, so one commit lands both. No package shipped
// with this build asks for that, which is why nothing claims a live result for it. Under
// merge, so the list is M7's; a replace sends the bootstrap whatever the manifest says
// (TestPushConfigReplaceExplicit).
func TestPushConfigSendsTheBootstrapByEitherMechanism(t *testing.T) {
	node := &pushNode{answer: committed}
	a, in, _ := pushSetup(t, node)
	in.Push.Mode = psp.ModeMerge
	stagePush(t, a, stagedBundle{artifact: pushArtifact, bootstrap: pushBootstrap, via: psp.BootstrapViaPush})

	if _, _, err := pushOnce(t, a, in); err != nil {
		t.Fatal(err)
	}
	bootstrap := texts(configCommands([]byte(pushBootstrap), true))
	want := append([]string{cmdEnterCandidate}, bootstrap...)
	want = append(append(want, artifactLines()...), cmdCommitNow)
	if !reflect.DeepEqual(node.commands[0], want) {
		t.Errorf("node was sent %q,\nwant %q", node.commands[0], want)
	}
}

// A staged bundle whose manifest cannot be read, or does not name the node, is a push
// that no retry can make: it is named and nothing is sent. bundle.Verify refuses both
// before the run, so reaching either means the staged copy changed since.
func TestPushConfigNamesAStagedManifestItCannotUse(t *testing.T) {
	for _, c := range []struct {
		name  string
		spoil func(t *testing.T, a *Activities, in *wire.PushInput)
		want  string
	}{
		{name: "no manifest", want: "reading the bundle manifest",
			spoil: func(t *testing.T, a *Activities, _ *wire.PushInput) {
				if err := os.Remove(filepath.Join(a.Paths.Twin, "bundle", compiler.ManifestFile)); err != nil {
					t.Fatal(err)
				}
			}},
		{name: "the node is not named", want: "the staged manifest does not name node n9",
			spoil: func(_ *testing.T, _ *Activities, in *wire.PushInput) { in.Node = "n9" }},
		{name: "the bootstrap is gone", want: "reading the staged bootstrap",
			spoil: func(t *testing.T, a *Activities, _ *wire.PushInput) {
				stagePush(t, a, stagedBundle{artifact: pushArtifact, bootstrap: pushBootstrap, via: psp.BootstrapViaPush})
				if err := os.Remove(filepath.Join(a.Paths.Twin, "bundle", "configs", "n1.cli")); err != nil {
					t.Fatal(err)
				}
			}},
	} {
		t.Run(c.name, func(t *testing.T) {
			node := &pushNode{answer: committed}
			a, in, log := pushSetup(t, node)
			c.spoil(t, a, &in)
			_, _, err := pushOnce(t, a, in)
			f := stepFailure(t, err, findings.RulePushFailed)
			if !strings.Contains(f.Message, c.want) || len(node.commands) != 0 {
				t.Errorf("finding %+v after %d requests, want %q and nothing sent", f, len(node.commands), c.want)
			}
			noContent(t, "an unusable staged manifest", f.Message, err.Error(), log.String())
		})
	}
}
