#!/usr/bin/env bash
# Writes the two generated diagrams, as Mermaid, from the tree alone:
#
#   - the import graph of the module's packages, between the <!-- import-graph --> and
#     <!-- /import-graph --> markers in docs/development.md, and nothing else of that file;
#   - docs/diagrams/topologies.md, the three golden bundles' topologies.
#
# Run by `make diagrams`, after the C4 exports. Needs go, awk and sha256sum. It reads
# testdata/golden/ and writes nothing under it. Its output is sorted and carries no
# timestamp, so a second run changes nothing.
set -euo pipefail

cd "$(dirname "$0")/.."
export LC_ALL=C

guide=docs/development.md
topologies=docs/diagrams/topologies.md
goldens=(three-node lossy mixed)

# A Mermaid node id for a path: letters, digits and underscores only.
mermaid_id() {
	printf '%s' "$1" | tr -c 'A-Za-z0-9_' '_'
}

# The import graph. One node per package of the module (the root package as "fylgja"),
# one edge per import of one module package by another. The client's side of the API
# boundary is a subgraph of its own.
import_graph() {
	local module edges pkgs p id
	module=$(go list -m)
	edges=$(go list -f '{{.ImportPath}} {{join .Imports " "}}' ./... |
		awk -v m="$module" '
			function rel(p) { return p == m ? "fylgja" : substr(p, length(m) + 2) }
			{
				print "P " rel($1)
				for (i = 2; i <= NF; i++)
					if ($i == m || index($i, m "/") == 1) print "E " rel($1) " " rel($i)
			}' | sort -u)
	pkgs=$(printf '%s\n' "$edges" | awk '$1 == "P" { print $2 }')

	echo '```mermaid'
	echo 'graph LR'
	echo "    subgraph client [\"the client's side\"]"
	for p in internal/api internal/cli internal/findings internal/tree; do
		printf '%s\n' "$pkgs" | grep -qx "$p" || {
			echo "scripts/diagrams.sh: package $p is not in the module" >&2
			exit 1
		}
		echo "        $(mermaid_id "$p")[\"$p\"]"
	done
	echo '    end'
	while read -r p; do
		case $p in
		internal/cli | internal/api | internal/tree | internal/findings) continue ;;
		esac
		echo "    $(mermaid_id "$p")[\"$p\"]"
	done <<<"$pkgs"
	printf '%s\n' "$edges" | awk '$1 == "E" { print $2, $3 }' | while read -r from to; do
		echo "    $(mermaid_id "$from") --> $(mermaid_id "$to")"
	done
	echo '```'
}

# Replaces what lies between the two markers in the development guide, and nothing else.
write_import_graph() {
	local graph tmp
	graph=$(import_graph)
	grep -qx '<!-- import-graph -->' "$guide" && grep -qx '<!-- /import-graph -->' "$guide" || {
		echo "scripts/diagrams.sh: $guide lacks the import-graph markers" >&2
		exit 1
	}
	# Written through a copy, then back over the guide, so the guide keeps its mode.
	tmp=$(mktemp)
	GRAPH="$graph" awk '
		$0 == "<!-- import-graph -->" { print; print ENVIRON["GRAPH"]; skip = 1; next }
		$0 == "<!-- /import-graph -->" { skip = 0 }
		!skip { print }' "$guide" >"$tmp"
	cat "$tmp" >"$guide"
	rm -f "$tmp"
}

# A bundle's id, by the recipe internal/bundle/id.go documents: the SHA-256 of
# sha256sum's listing of every regular file, in byte-wise path order.
bundle_id() {
	(cd "$1" && find . -type f | sed 's|^\./||' | sort | xargs sha256sum | sha256sum | cut -d' ' -f1)
}

# One golden's topology: a node per containerlab node, labelled with its kind, and an
# undirected edge per link, labelled with both endpoints as the topology spells them.
topology_graph() {
	local topo=$1
	echo '```mermaid'
	echo 'graph LR'
	awk '
		/^  nodes:/ { section = "nodes"; next }
		/^  links:/ { section = "links"; next }
		section == "nodes" && /^    [^ ].*:$/ { name = $1; sub(/:$/, "", name); next }
		section == "nodes" && /^      kind:/ { kind[++n] = $2; node[n] = name; next }
		section == "links" && /endpoints:/ {
			line = $0
			sub(/.*\[/, "", line); sub(/\].*/, "", line); gsub(/[" ]/, "", line)
			split(line, ends, ",")
			a = ends[1]; b = ends[2]
			na = a; sub(/:.*/, "", na); nb = b; sub(/:.*/, "", nb)
			link[++l] = sprintf("    n_%s ---|\"%s — %s\"| n_%s", na, a, b, nb)
		}
		END {
			for (i = 1; i <= n; i++) printf "    n_%s[\"%s (%s)\"]\n", node[i], node[i], kind[i]
			for (i = 1; i <= l; i++) print link[i]
		}' "$topo"
	echo '```'
}

write_topologies() {
	local g text
	mkdir -p "$(dirname "$topologies")"
	text=$({
		echo '# The fixture topologies'
		echo
		echo 'Generated by `scripts/diagrams.sh` from each golden bundle under `testdata/golden/`:'
		echo "its \`topology.clab.yml\` and its \`bundle_id\`. Regenerate it with \`make diagrams\`;"
		echo 'never edit it by hand. Each node is labelled with its containerlab kind, and each link'
		echo 'with its two endpoints as the topology names them.'
		for g in "${goldens[@]}"; do
			echo
			echo "## $g — \`$(bundle_id "testdata/golden/$g")\`"
			echo
			topology_graph "testdata/golden/$g/topology.clab.yml"
		done
	})
	printf '%s\n' "$text" >"$topologies"
}

write_import_graph
write_topologies
